# Generated by Django 3.2.8 on 2022-07-07 17:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='SecurityLayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('layer', models.CharField(max_length=40, verbose_name='layer')),
                ('scope', models.CharField(max_length=40, verbose_name='scope')),
                ('preceding_layer', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_layers', to='users.securitylayer', verbose_name='preceding layer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='security_layers', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'security layer',
                'verbose_name_plural': 'security layers',
            },
        ),
    ]
