# Generated by Django 3.0.4 on 2020-05-24 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True


    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=26, verbose_name='نام مطلب')),
                ('text', models.TextField( verbose_name='متن مطلب')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='ساخته شده در')),
            ],
        ),


        migrations.CreateModel(
            name='UserContentReview',
            fields=[
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,null=False, related_name='users', to='users.User', verbose_name='کاربران')),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,null=False, related_name='contents', to='contents.Content', verbose_name='مطالب')),
                ('star', models.IntegerField(verbose_name='امتیاز')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='ساخته شده در')),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='تغیر داده شده در')),
            ],

        ),
    ]

